### ISSUE TITLE
Scoped css required for build to succeed

### ISSUE THREAD

**Issue by hugh-maaskant** [McNerdius/TailBlazor#103]
Hi,

I manged to get it to work (on MacOs with Rider), but there is one gotcha: at least one scoped css file is needed, otherwise the dotNet build will not generate the /obj/scopedcss/bundle/{projectName}.styles.css file and the npm build will fail.

Maybe good to mention this in the documentation :-)

**Comment by McNerdius** [comment]
Indeed... i'll be sure to include this in the upcoming tailblazor.dev / templates.tailblazor.dev content refresh, thank you !

**Comment by McNerdius** [comment]
I've refreshed the howto and template sites a bit and now point this out:

https://www.tailblazor.dev/tidy_css

https://templates.tailblazor.dev/info

😃

**Comment by hugh-maaskant** [comment]
Great, thanks :-)

——
Hugh Maaskant
The Netherlands
