### ISSUE TITLE
Question: Blazor Hot Reload + Tailwind JIT

### ISSUE THREAD

**Issue by sh-jthorpe** [McNerdius/TailBlazor#37]
Hi there,

Thank you so much for sharing information on this, it's very difficult to find info about this.

I've got a question for you - did you not run into the below issue with Blazor Hot Reload and Tailwind JIT?

https://github.com/dotnet/aspnetcore/issues/34116

I'm using the same approach as you (`npx tailwind --watch` and `dotnet watch run`) just without using VScode to run the commands. I did try cloning your TailBlazorLite repo and giving it a spin, but I had some issues, and figured I'm using the same approach, no reason it should work differently.

Feel free to close if not relevant, just thought i'd ask!

**Comment by McNerdius** [comment]
Out of about 20-30 tries, i was able to reproduce the "not applying back to back changes" four times.  Experiences seem to differ beyond that though... My experience with editing `*.razor` files (as opposed to `*.razor.css`) has been that at least half the time, it is considered a "rude edit" and trigger a full rebuild.  (Interestingly, using `dotnet watch run --verbose` i didn't face the known issue [mentioned here](https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-preview-5/#net-hot-reload-updates-for-dotnet-watch).  Note to self...)  That even a full rebuild doesn't pick up the newest CSS is pretty odd.  

What version of Tailwind are you on ?  I noticed, when i first upgraded to 2.2.0, `tailwind` and `tailwindcss` CLI behaved differently.  It seems this is no longer the case with 2.2.4.  I only ask because you mentioned `npx tailwind --watch` and it seems i'm not seeing the "fast edits" issue quite as much.

But i haven't seen this in my day to day editing, no... i don't type that fast hehe.

TailBlazorLite does need some attention indeed... It's probably in a "works on my machine" state.  I put that on the back burner until i got TailBlazor to where it is now, with the new project/folder naming.  (Issues #5 & #34 will have to wait...)

**Comment by McNerdius** [comment]
So, this is what's going on on my end...

A normal edit/re-render cycle would look like this:

![normal](https://i.imgur.com/TPpNtBt.png)

`dotnet watch` sees my edits, Hot Reload spits out a new Isolated bundle (`*.styles.css`).  `tailwindcss --watch` sees the new bundle, spits out a new `site.min.css`.  `dotnet watch` sees a new `site.min.css`, Hot Reload swaps it in and re-renders.

---

But, when edits are done super-fast, Tailwind is still in the middle of churning out a new `site.min.css` as `dotnet watch` is outputting the second Isolated bundle:

![fast](https://i.imgur.com/boZrptd.png)

---

Not sure if this is what you're seeing as well, but that's whats going on here.

([drawio extension](https://marketplace.visualstudio.com/items?itemName=hediet.vscode-drawio) for the win.)

**Comment by McNerdius** [comment]
Perhaps coincidentally, my Tailwind incremental [build times](https://i.imgur.com/6s2PeQ9.png) average about 80ms.  Suspiciously close to the 75ms mentioned in the issue you linked.  🤔

**Comment by sh-jthorpe** [comment]
I appreciate you taking the time to look at this!

> Out of about 20-30 tries, i was able to reproduce the "not applying back to back changes" four times. Experiences seem to differ beyond that though... My experience with editing *.razor files (as opposed to *.razor.css) has been that at least half the time, it is considered a "rude edit" and trigger a full rebuild. (Interestingly, using dotnet watch run --verbose i didn't face the known issue mentioned here. Note to self...) 

I know there's more work to do around rude edits. One that I ran into was that RenderFragment parameters (ie ChildContent) aren't supported yet (https://github.com/dotnet/runtime/issues/51126#issuecomment-817168343). Hopefully you'll have a better experience once they improve that.

I suppose you would only see the same issue if your isolated bundle `*.styles.css` and `site.min.css` are being generated within a short enough period of time. That you only saw the issue 4 out of 20-30 supports that. I'm seeing my tailwind CSS rebuild within 40-50ms so I think you're lucky that it's taking slightly longer to compile!

> What version of Tailwind are you on ? I noticed, when i first upgraded to 2.2.0, tailwind and tailwindcss CLI behaved differently. It seems this is no longer the case with 2.2.4. I only ask because you mentioned npx tailwind --watch and it seems i'm not seeing the "fast edits" issue quite as much.

Sorry that was a typo. I'm using 2.2.4 and I meant to type `npx tailwindcss --watch`. I'm using the same command as your `npm run watch-wasm`.

The issue isn't specific to tailwind, because I was able to reproduce it by editing two Razor files. Unfortunately for Tailwind/Blazor users, it's more likely to affect them, and if it does, it can be pretty annoying.


I have two ideas to fix this. Either workaround it by adding an artificial delay to the tailwind CSS compilation, or maybe fix the issue with Hot Reload. Either way, i'll let you know what happens.

**Comment by sh-jthorpe** [comment]
Alright, so I went with a simple option (but still a hack!). A Powershell script that watches the compiled CSS, and appends an empty space (` `) to the file to trigger Hot Reload.

I'll still have a look at solving the actual problem, but this serves as an unobtrusive workaround for the meantime.


StartDev.ps1
```Powershell
# This could be done through VSCode tasks.
powershell.exe -WindowStyle hidden -file "Scripts\WatchFileChange.ps1"
Start-Process -NoNewWindow "npm run buildcss:watch"
```

WatchFileChange.ps1
```Powershell
Write-Host "Started"
$File = ".\wwwroot\css\app.css" # Path to your compiled Tailwind CSS.

while ($true) {
    $Before = (Get-Item $File).LastWriteTime
    Start-Sleep -Milliseconds 400
    $After = (Get-Item $File).LastWriteTime
    if ($Before -ne $After) {
        Write-Host "File changed $(Get-Date)"
        " " | Add-Content $File
    } 
}
```

**Comment by McNerdius** [comment]
Hey i went ahead and did a fresh clone of TailBlazor-Lite on another machine.  I didn't have any issues other than the potential "must `dotnet build` before `npx tailwindcss` b/c CSS references generated files" thing.  Not sure if this is the issue you were facing but regardless i've made changes to both repos [described here](https://github.com/McNerdius/TailBlazor/blob/main/CHANGELOG.md#vnext).  If that's not what you were up against, open an issue on that repo if you want.

**Comment by sh-jthorpe** [comment]
Hey, I'll give it a try and let you know. Cheers

**Comment by McNerdius** [comment]
And now... just put a TailBlazorLite update up, step #1 in getting a `dotnet new tailblazor` template package out there.  It comes with its own build/run quirk i haven't pinned down yet: getting intermittent "hostpolicy.dll not found" error i can't reproduce consistently.  Rebuild makes it go away though.
