### ISSUE TITLE
 virtual DOM  problem 

### ISSUE THREAD

**Issue by SalimiHabib** [McNerdius/TailBlazor#92]
Will your  approach for tailwind integration  solve the  virtual DOM  problem ?

**Comment by McNerdius** [comment]
Sorry for delay, i had to step away from code and work on content a bit.  Doing some reading up on virtual DOM as it relates to Blazor i can't say i understand what problem.  Nothing really special is happening here client-wise, just connecting the tools to take full advantage of what Blazor and Tailwind's new CLI/JIT/Incremental builds offer.
